Add bancontact payment
rikva/voko pull request #159
Opened 2021-04-17 19:35 UTC by mgvd

Er is een extra stap in de betaalflow toegevoegd, nl kies een betaalmethode. Dit is nu de eerste stap als men wil betalen.

Indien iDeal, dan kan de gebruiker alsnog een bank kiezen, zoals in huidige flow. In het geval van Bancontact, dan gaat de gebruiker direct offsite om de betaling te doen.

finance/tests ook aangepast en aangevuld

Lokaal getest met test API key van Mollie

2021-04-18 08:29 UTC, rikva commented
De code ziet er goed uit, maar waarom hebben we als Utrechts collectief behoefte aan een Belgische betaalmethode? 😄

2021-04-18 09:47 UTC, mgvd commented
De vraag is vaker langs gekomen en het leek een niet al te ingrijpende toevoeging. Achteraf toch meer werk dan ik dacht. Nu is het wel relatief eenvoudig om andere betaalmethodes toe te voegen. 
Ik zal een issue aanmaken om de Mollie api te updaten. Tussen 1.x en 2.x zitten veel wijzigingen, dat kon ik niet gelijk meenemen.

2021-04-27 17:13 UTC, rikva requested changes
Ik snap waarom je het zo gemaakt hebt, maar de manier waarop je nu views _in andere views_ rendert vind ik lastig om akkoord mee te gaan. IMO moet een view op één URL beschikbaar zijn. 

Is het een idee om de Bancontact keuze toe te voegen aan de `ChooseBankView`? Bijv met een radio button of desnoods als extra optie in de dropdown. Je kunt dan nog steeds POSTen naar `CreateTransactionView`, alwaar je alleen even hoeft te checken of het iDEAL of Bancontact wordt. Misschien zie ik iets over het hoofd, maar ik denk dat het op die manier minder complex wordt dan wat je nu voorstelt.

2021-05-03 18:12 UTC, mgvd commented
Goede suggesties, ik heb de choose payment method stap er uit gehaald en de code vereenvoudigd. De gebruiker kan direct zijn bank kiezen als hij iDeal aanklikt (default geselecteerd)

2021-05-13 15:00 UTC, mgvd commented
Ik heb view.py opgeruimd van onnodige comments en post method

2021-05-13 18:25 UTC, merged

2021-05-13 18:26 UTC, rikva commented
Top! Deployed naar productie.